version: '3.2'

networks:
  laravel:

services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    container_name: versite_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:14.7-alpine
    container_name: versite_postgres
    tty: true
    ports:
      - "6432:5432"
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - laravel

  php:
    build:
      context: ./
      dockerfile: dockerfiles/php.dockerfile
    container_name: versite_php
    volumes:
      - ./src/app:/var/www/html/app
      - ./src/bootstrap:/var/www/html/bootstrap
      - ./src/storage:/var/www/html/storage
      - ./src/config:/var/www/html/config
      - type: bind
        source: ./src/.env
        target: /var/www/html/.env
    networks:
      - laravel


volumes:
  psql:
